# Generated by Django 5.1.6 on 2025-02-16 15:17

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[("typing", "Typing Test"), ("steno", "Steno Test")],
                        default="typing",
                        max_length=10,
                    ),
                ),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="steno_audio/"),
                ),
                ("is_timed", models.BooleanField(default=True)),
                ("time_limit", models.IntegerField(blank=True, null=True)),
                ("is_backspace_allowed", models.BooleanField(default=True)),
                ("is_case_sensitive", models.BooleanField(default=False)),
                ("max_score", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("time_taken", models.IntegerField(help_text="Time taken in seconds")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("user_input", models.TextField()),
                ("extra_info", models.JSONField(blank=True, null=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="test_series.test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="test",
            name="test_series",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="test_series.testseries",
            ),
        ),
    ]
