# Generated by Django 5.1.6 on 2025-02-16 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_series", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="test_series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="test_series.testseries",
            ),
        ),
    ]
