# Generated by Django 5.1.6 on 2025-02-17 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("test_series", "0003_course_coursetopic_remove_test_test_series_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="topic",
        ),
        migrations.AlterField(
            model_name="test",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="courses.course",
            ),
        ),
        migrations.RemoveField(
            model_name="coursepurchase",
            name="course",
        ),
        migrations.RemoveField(
            model_name="coursebundle",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="coursepurchase",
            name="bundle",
        ),
        migrations.RemoveField(
            model_name="coursepurchase",
            name="user",
        ),
        migrations.DeleteModel(
            name="CourseTopic",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="CourseBundle",
        ),
        migrations.DeleteModel(
            name="CoursePurchase",
        ),
    ]
